---
- hosts: all
  tasks:
    - name: install applications via homebrew cask
      homebrew_cask: name={{ item }} state=present
      with_items:
        - firefox
        - xld
        - vlc
        #- flux
        - java
        - netbeans
        - handbrake
        #- sequel-pro
        - mysqlworkbench
        - the-unarchiver
        - virtualbox
        - vagrant
        - vagrant-manager
        - torbrowser
        - github
        - little-snitch
        - google-chrome
        - iterm2
        - musicbrainz-picard
        - atom
        - packer
      environment:
        HOMEBREW_CASK_OPTS: --appdir=/Applications

    - name: install brew applications
      homebrew: name={{ item }} state=latest
      with_items:
        - pv
        - mysql
        - pigz
